# Generated by Django 3.2.15 on 2022-10-13 04:38

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', jsonfield.fields.JSONField(default=dict)),
                ('formname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formname')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', jsonfield.fields.JSONField(default=dict)),
                ('label', jsonfield.fields.JSONField(default=dict)),
                ('more_field', jsonfield.fields.JSONField(default=dict)),
                ('field_type', models.CharField(max_length=100, null=True)),
                ('formname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formname')),
            ],
        ),
    ]
